description = "Peter Raucher's Blog"
[social]
github = "peterrauscher"
linkedin = "peter-rauscher"
email = "contact@peterrauscher.com"
[author]
name = "Peter Raucher"
email = "contact@peterrauscher.com"
